openconnect: add dependency to fix Makefile.am
main.c needs version.c which is generated at build time.
Add this dependency to avoid the following error.

  ../git/main.c:78:21: fatal error: version.c: No such file or directory

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>